import React, { useState, useEffect } from "react";
import "react-toastify/dist/ReactToastify.css";
import Header from "./Header";
import Head from "next/head";
import Image from "next/image";
import useAdminStore from "@/store/admin/adminStore";
import Sidebar from "./Sidebar";

export default function AdminLayout({ children }) {
  const [isLoading, setIsLoading] = useState(true);
  const { isAdmin } = useAdminStore();
  const [clickedTitle, setClickedTitle] = useState("");

  const handleTitleClick = (title) => {
    setClickedTitle(title);
  };

  useEffect(() => {
    const timer = setTimeout(() => {
      setIsLoading(false);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  if (isLoading) {
    return (
      <div className="flex justify-center items-center h-screen">
        <div className="animate-spin rounded-full h-20 w-20 border-t-2 border-b-2 border-gray-900"></div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Artsbyart - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen font-opensans bg-white flex">
        <aside className="w-[232px] hidden lg:block text-center mx-auto text-secondary bg-white border-r border-solid 2xl:w-[263px]">
          <Image
            src="https://res.cloudinary.com/dgms1mpbw/image/upload/v1699825747/ARTS_BY_ART_LOGO_ydpcyd_nzavtb.png"
            width={170}
            height={0}
            alt="logo"
            className=""
          />
          <Sidebar onTitleClick={handleTitleClick} />
        </aside>
        <main className="flex-1 mt-8 px-6 flex flex-col">
          <Header clickedTitle={clickedTitle} />
          {children}
        </main>
      </div>
    </>
  );
}
