import Head from "next/head";
import React from "react";
import Navbar from "../Homepage/Navbar";
import Mobilenav from "../Homepage/Mobilenav";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Artsbyart</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Mobilenav />
      <main className="lg:mt-[7rem]">{children}</main>
    </div>
  );
};

export default Layout;
