import { getUserFromLocalStorage } from "@/utils/Localstorage";
import Head from "next/head";
import React, { useState, useEffect } from "react";
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const Profile = () => {
  const [password, setPassword] = useState("");
  const [phone, setPhone] = useState("");

  useEffect(() => {
    const parsedUser = getUserFromLocalStorage();
    const userId = parsedUser?.newUser?._id;
    if (!userId) {
      throw new Error("User ID not found in localStorage");
    }
    // Fetch user data
    fetch(`/api/users/userdetails?userId=${userId}`)
      .then((response) => response.json())
      .then((data) => {
        const user = data.user;
        setPhone(user.phone);
      })
      .catch((error) => {
        console.error(error);
      });
  }, []);

  const handleUpdate = (e) => {
    e.preventDefault();
    const parsedUser = getUserFromLocalStorage();
    const userId = parsedUser?.newUser?._id;
    if (!userId) {
      throw new Error("User ID not found in localStorage");
    }
    // Update user data
    fetch(`/api/users/userdetails?userId=${userId}`, {
      method: "PUT",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        userId,
        password,
        phone,
      }),
    })
      .then((response) => response.json())
      .then(() => {
        toast.success("User information updated successfully");
      })
      .catch((error) => {
        console.error(error);
        toast.error("An error occurred while updating user information");
      });
  };

  return (
    <div>
      <Head>
        <title>Artsbyart - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="px-12 mt-8">
        <h1 className="font-gilmerbold md:text-[25px]">Edit Account</h1>
        <form className="font-gilmermedium" onSubmit={handleUpdate}>
          <div className="flex md:flex-row flex-col md:mt-6 items-center justify-between">
            <div className="text-start md:mt-0 mt-4 flex flex-col">
              <label>New Password</label>
              <input
                type="password"
                value={password}
                readOnly
                className="md:w-[500px] w-[320px] focus:outline-none border border-solid py-3 mt-2 px-4"
              />
            </div>
            <div className="text-start md:mt-0 mt-4 flex flex-col">
              <label>Phone Number</label>
              <input
                type="number"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                className="md:w-[500px] w-[320px] focus:outline-none border border-solid py-3 mt-2 px-4"
              />
            </div>
          </div>

          <button
            type="submit"
            className=" focus:outline-none border border-solid bg-primary text-light py-3 mt-8 px-4"
          >
            Update
          </button>
        </form>
      </div>
    </div>
  );
};

export default Profile;
